export { MainPage } from './MainPage/MainPage';
export { InfoPage } from './InfoPage/InfoPage';
export { LoginPage } from './LoginPage/LoginPage';
export { RegPage } from './RegPage/RegPage';
export { MainMenuPage } from './MainMenuPage/MainMenuPage';
export { StatsPage } from './StatsPage/StatsPage';
export { GamePage } from './GamePage/GamePage';
export { BoomerangPage } from './BoomerangPage/BoomerangPage';
export { RPGPage } from './RPGPage/RPGPage';