export { Navbar } from './Navbar/Navbar'
export { LoginForm } from './LoginForm/LoginForm'
export { RegForm } from './RegForm/RegForm'
export { MainMenu } from './MainMenu/MainMenu'
export { Stats } from './Stats/Stats'
export { Game } from './Game/Game'